### ISSUE TITLE
Add constness to IRunnable::run

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/tools#10]
The input vector should be `const`ed:

https://github.com/roboticslab-uc3m/tools/blob/f08b255803fcce5bd18bd2259111eb6b1fc1e0f3/libraries/YarpPlugins/IRunnable.h#L22

**Comment by jgvictores** [comment]
Maybe in examplePlaybackThread too?

**Comment by PeterBowman** [comment]
Oops, I totally overlooked that in the grep results. Thanks for noticing, @jgvictores!

PS: it's a pity that Travis does not cover examples, too ([YARP actually builds its OS examples](https://github.com/robotology/yarp/blob/40f73b4840663b5d7769d659d8f92cea53f52e35/.travis.yml#L406-L409)).

**Comment by jgvictores** [comment]
Thanks for fixing!!
