### ISSUE TITLE
Convert index-based for loops to STL iterators in libraries/Playback

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/tools#6]
Convert index-based for loops to STL iterators in [libraries/Playback](https://github.com/roboticslab-uc3m/tools/tree/d42f1b92949c67db467f07e23b9df791fbd4e718/libraries/Playback).

**Comment by jgvictores** [comment]
Iterator is currently [an integer](https://github.com/roboticslab-uc3m/tools/blob/350626b85cc2bdc37a771b939fdab90b69f6ae41/libraries/Playback/Playback.hpp#L57).

**Comment by jgvictores** [comment]
An interesting macro at [libopenrave.h](https://github.com/rdiankov/openrave/blob/284027a1bb6f4c5dae294854d01b5bbd641c8a3c/src/libopenrave/libopenrave.h#L55):
```cpp
#define FOREACH(it, v) for(typeof((v).begin())it = (v).begin(), __itend__=(v).end(); it != __itend__; (it)++)
```

**Comment by David-Estevez** [comment]
I think that feature is already [supported by C++11](http://en.cppreference.com/w/cpp/language/range-for).

**Comment by jgvictores** [comment]
That's interesting! Thanks for the reference!!

**Comment by PeterBowman** [comment]
I'm quite used to the way iterators work in Java, and so I decided to reflect that in the new Playback API by means of the methods `hasNextRow` and `getNextRow`. Internally, though, it is now using a constant iterator for keeping track of the progress: https://github.com/roboticslab-uc3m/tools/commit/4ed1994afb84e3a2cc792e521a2a08649d5be384.

Sample usage:

https://github.com/roboticslab-uc3m/tools/blob/8680552d876cb05261ed397c4909b0bcd2225651/tests/testPlayback.cpp#L50-L53

Note `getCurrentRowIndex()` will yield a different result depending on whether it is called before or after `getNextRow()`, which internally advances the forward iterator.
