### ISSUE TITLE
OpenRave to stl script uncorrect README.md file

### ISSUE THREAD

**Issue by AlvaroMartinezR** [roboticslab-uc3m/tools#9]
I noticed that [here](https://github.com/roboticslab-uc3m/tools/tree/develop/programs/openraveppToSTL#how-to-use-it), 
```
python openravepp-to-stl.py 
```
should be named 
```
 openraveppToSTL.py
```

**Comment by RaulFdzbis** [comment]
Yes, you are right, thank you for discovering the bug! :D
